"""Hospital uncompensated care generated by the Mexican-origin union, CPS ASEC 2025 (income year 2024).

Reuses the complete account's canonical target (full_account_spending_2026_09_20/builder.py) and the
per-uninsured-person-year price pinned in ledger_residual_micro_2026_09_16 (AHA $42.67bn / Census
28.0m uninsured = $1,524; x1.20 for 2024 hospital input prices). Exposure = full-year uninsured
(NOCOV_CYR 3) + half of part-year uninsured (NOCOV_CYR 2), as in that lane. SDR standard errors
from the 160 ASEC replicate weights.
"""
import importlib.util
import json
import sys
import zipfile
from pathlib import Path

import numpy as np
import pandas as pd

HERE = Path(__file__).resolve().parent
FISCAL = HERE.parent
spec = importlib.util.spec_from_file_location(
    "account_builder", FISCAL / "full_account_spending_2026_09_20" / "builder.py")
builder = importlib.util.module_from_spec(spec)
spec.loader.exec_module(builder)

sys.path.insert(0, str(FISCAL / "ledger_residual_micro_2026_09_16"))
import residual_micro as rm  # noqa: E402  (price constants only; no build is run)

PRICE = rm.UNCOMPENSATED_PER_UNINSURED
UPLIFT = rm.UNCOMPENSATED_2024_UPLIFT
PER_HEAD_SHARE = 0.120245  # complete account's population key x pool fraction (cj_use_allocation key_inputs)
TARGET_TOTAL = 40_896_574.15235156

archive = FISCAL / "gen_ledger_extension_2026_09_16" / "_cache" / "asecpub25csv.zip"
assert builder.sha(archive) == builder.CPS_SHA, "CPS source changed"
fields = ["PH_SEQ", "PPPOS", "A_AGE", "PRPERTYP", "PRCITSHP", "PENATVTY", "PEFNTVTY", "PEMNTVTY",
          "PRDTHSP", "NOCOV_CYR", "COV", "MCAID"]
reps = ["pwwgt0"] + [f"pwwgt{i}" for i in range(1, 161)]
with zipfile.ZipFile(archive) as z:
    d = pd.read_csv(z.open("pppub25.csv"), usecols=fields)
    w = pd.read_csv(z.open("asec_csv_repwgt_2025.csv"), usecols=["h_seq", "PPPOS"] + reps).rename(
        columns={"h_seq": "PH_SEQ"})
d = d.merge(w, on=["PH_SEQ", "PPPOS"], validate="one_to_one", how="left")
assert not d[reps].isna().any().any(), "missing replicate weights"

civ, target = builder.canonical_target(d)
mexico_born = target & (d.PRCITSHP.isin([4, 5]) & d.PENATVTY.eq(303)).to_numpy()
W = d[reps].to_numpy(float)
total = W[target, 0].sum()
assert abs(total - TARGET_TOTAL) < 0.01, f"canonical target {total:,.2f}"
print(f"  ✓ canonical target = {total:,.2f}")

exposure = d.NOCOV_CYR.eq(3).to_numpy(float) + 0.5 * d.NOCOV_CYR.eq(2).to_numpy(float)
medicaid = d.MCAID.eq(1).to_numpy(float)
groups = {"target": target, "target_mexico_born": mexico_born, "target_us_born": target & ~mexico_born,
          "other_civilian": civ & ~target, "all_civilian": civ}


def sdr_se(est):  # est: array over 161 weights, column 0 the full sample
    return float(np.sqrt(4 / 160 * ((est[1:] - est[0]) ** 2).sum()))


all_py = (W[civ] * exposure[civ, None]).sum(0)
all_mcaid = (W[civ] * medicaid[civ, None]).sum(0)
rows = []
for name, m in groups.items():
    persons = W[m].sum(0)
    py = (W[m] * exposure[m, None]).sum(0)
    share = py / all_py
    rate = py / persons
    mshare = (W[m] * medicaid[m, None]).sum(0) / all_mcaid
    rows.append(dict(group=name, persons_m=persons[0] / 1e6, uninsured_person_years_m=py[0] / 1e6,
                     uninsured_rate=rate[0], uninsured_rate_se=sdr_se(rate),
                     share_of_uninsured_py=share[0], share_se=sdr_se(share),
                     share_of_medicaid_covered=mshare[0],
                     cost_bn_price2020=py[0] * PRICE / 1e9, cost_bn_2024=py[0] * PRICE * UPLIFT / 1e9,
                     cost_bn_2024_se=sdr_se(py * PRICE * UPLIFT / 1e9)))
out = pd.DataFrame(rows)
(HERE / "derived").mkdir(exist_ok=True)
out.round(6).to_csv(HERE / "derived" / "uncompensated_by_group.csv", index=False)

t = out.set_index("group")
# Central: the target's share of uninsured person-years applied to AHA's national total, so the
# national figure stays AHA's. The price x exposure method overshoots it, because CPS 2024
# exposure (full year + half of part year) exceeds P60's 28.0m full-year count the price divides by.
aha_bn = rm.AHA_UNCOMPENSATED_2020 / 1e9
share = t.loc["target", "share_of_uninsured_py"]
summary = dict(
    aha_national_bn=aha_bn, uplift_2024=UPLIFT,
    target_share=share, target_share_se=t.loc["target", "share_se"],
    target_bn=share * aha_bn, target_bn_2024_prices=share * aha_bn * UPLIFT,
    per_head_bn=PER_HEAD_SHARE * aha_bn, per_head_bn_2024_prices=PER_HEAD_SHARE * aha_bn * UPLIFT,
    excess_over_per_head_bn=(share - PER_HEAD_SHARE) * aha_bn,
    excess_over_per_head_bn_2024_prices=(share - PER_HEAD_SHARE) * aha_bn * UPLIFT,
    target_share_of_medicaid_covered=t.loc["target", "share_of_medicaid_covered"],
    check_price_x_exposure_national_bn=t.loc["all_civilian", "cost_bn_price2020"],
    check_price_x_exposure_target_bn=t.loc["target", "cost_bn_price2020"])

# What the account misses. Governments offset a share g of providers' uncompensated care
# (Urban Institute: 0.65 in 2013, about 0.80 in 2017). That part is inside the account but keyed
# at k, per head (0.120) or the target's Medicaid-coverage share (0.196), not its uninsured share.
# The rest (1 - g) is borne by hospitals, physicians and private payers, outside any fiscal account.
# Added cost to other residents = s*N - g*k*N. Use intensity r rescales the target's person-years.
py_t = t.loc["target", "uninsured_person_years_m"]
py_o = t.loc["other_civilian", "uninsured_person_years_m"]
arms = []
for r in (1.0, 0.7):
    s_r = r * py_t / (r * py_t + py_o)
    for label, n, g, k in (("low", aha_bn, 0.80, t.loc["target", "share_of_medicaid_covered"]),
                           ("high", aha_bn * UPLIFT, 0.65, PER_HEAD_SHARE)):
        arms.append(dict(use_intensity=r, arm=label, national_bn=n, gov_offset_share=g, key_share=k,
                         target_share=s_r, target_bn=s_r * n, outside_accounts_bn=(1 - g) * s_r * n,
                         inside_misallocated_bn=g * (s_r - k) * n, added_cost_bn=s_r * n - g * k * n))
pd.DataFrame(arms).round(4).to_csv(HERE / "derived" / "added_cost_arms.csv", index=False)
print(pd.DataFrame(arms).round(2).to_string(index=False))
(HERE / "derived" / "summary.json").write_text(json.dumps(summary, indent=1))
print(out.round(3).to_string(index=False))
print(json.dumps(summary, indent=1))
