"""Write design_eu.csv from the ROWS list below (one dict per study, filled from primary text).

Run from the repo root:
  OPENBLAS_NUM_THREADS=1 uv run --no-project python3 infra/immigration-fiscal/school_systemwide_2026_09_27/design_table/build_design_eu.py
"""
import csv
from pathlib import Path

COLS = [
    "study", "citation", "country", "outcome_measure", "score_normalization_quote", "stakes",
    "comparison", "fixed_effects", "detects_systemwide_shift", "reason", "headline_estimate",
    "estimate_unit", "source_url", "source_locator", "quote",
]

ROWS = [
    dict(
        study="Brunello & Rocco 2013",
        citation="Brunello G., Rocco L. (2013), The effect of immigration on the school performance of natives: cross country evidence using PISA test scores, Economics of Education Review 32:234-246; read as IZA DP 5479 (Feb 2011)",
        country="27 countries (mainly Europe and Anglo-Saxon), PISA 2000/2003/2006/2009",
        outcome_measure="fixed absolute international scale (PISA): log of the country-mean score of native 15-year-olds, country x wave x subject cells",
        score_normalization_quote='"In all specifications we use the log test score as the dependent variable." (p. 10-11); "we enhance the comparability over time for each domain by retaining only the wave where it is treated as major and the following waves" (p. 8)',
        stakes="low-stakes (PISA sample survey; no consequences for pupils or schools) [TRAINING-DATA: the DP does not discuss stakes]",
        comparison="between countries/systems over time (within-country change across PISA waves, net of common wave effects)",
        fixed_effects="country, time (wave) and subject dummies; controls: GDP per capita level and growth, secondary spending per pupil, total immigrant stock, share of boys (x subject), average books; SE clustered by country x time; split-sample IV for measurement error (Table 4)",
        detects_systemwide_shift="Yes",
        reason="The outcome is a cross-wave linked absolute scale aggregated to the country, and identification comes from a country's change in immigrant share relative to other countries, so a level shift common to all schools in a country is exactly what it measures; wave dummies absorb only a shift common to all 27 countries at once.",
        headline_estimate="-0.275** (SE 0.135) on log native score per unit share, all natives; poor-background natives -0.409*** (0.155); good-background -0.171 (0.123); IV mean over 500 split-sample draws -0.281 [0.153] (Table 4). Per 10 pp: -2.75% of score (95% CI -0.8% to -5.4%) [CALCULATION]",
        estimate_unit="log points of the country-mean native PISA score per unit (0-1) immigrant-pupil share (first generation: born abroad of two foreign parents)",
        source_url="https://docs.iza.org/dp5479.pdf",
        source_locator="eq. (1) p. 6; data p. 8; Table 2 col. (1) p. 19 (printed page; notes 'each regression includes country, subject and time dummies'); Table 4 p. 21",
        quote='"We use repeated country observations over time and identify the relationship between the share of immigrants and the test scores of natives by exploiting the country by time variations in the data." (p. 6)',
    ),
    dict(
        study="Ohinata & van Ours 2013",
        citation="Ohinata A., van Ours J.C. (2013), How immigrant children affect the academic achievement of native Dutch children, Economic Journal 123(570):F308-F331; read as IZA DP 6212 (Dec 2011)",
        country="Netherlands, grade 4 (PIRLS 2001/2006 reading; TIMSS 1995/2007 maths and science)",
        outcome_measure="fixed absolute international scale (PIRLS/TIMSS plausible values, scale points), but each survey year estimated separately",
        score_normalization_quote='"plausible values are reported in PIRLS and TIMSS, which use multiple imputation to reveal how the students would have performed should they complete the entire tests" (p. 12); Table 5 note calls them "standardized test scores" [internal inconsistency; Table 4 coefficients are in points]',
        stakes="low-stakes (IEA sample survey) [TRAINING-DATA: the DP does not discuss stakes]",
        comparison="within school across classes (same grade, same year)",
        fixed_effects="school fixed effects; separate regression per survey year (so no cross-year variation used); pupil, family, class and teacher controls",
        detects_systemwide_shift="No",
        reason="Although the scale is absolute, identification is the difference between classes inside one school in one survey year, so any shift common to all Dutch schools is absorbed by the school effects and the per-year estimation.",
        headline_estimate="% immigrants in class: reading 2001 0.40 (0.29); reading 2006 -0.13 (0.28); science 1995 0.24 (0.38); science 2007 -0.31 (0.33); maths 1995 1.54*** (0.58); maths 2007 -0.23 (0.47). Without school FE reading 2001 -0.95*** (0.16) (Table 5 row b)",
        estimate_unit="PIRLS/TIMSS scale points per 1 pp of immigrant (1st+2nd generation) share in the class",
        source_url="https://docs.iza.org/dp6212.pdf",
        source_locator="identification p. 15; plausible values p. 12; Table 4 (pdf p. 30, printed p. 28); separate-year estimation p. 16",
        quote='"The main identification assumption requires that once school specific characteristics are controlled for, students are allocated to each class randomly within a school" (p. 15); "separate regressions are estimated for each year" (p. 16)',
    ),
    dict(
        study="Geay, McNally & Telhaj 2013",
        citation="Geay C., McNally S., Telhaj S. (2013), Non-native speakers of English in the classroom: what are the effects on pupil performance?, Economic Journal 123(570):F281-F307; read as IZA DP 6451 (Mar 2012)",
        country="England, Year 6 (age 11), National Pupil Database census, cohorts 2003-2009",
        outcome_measure="percentile rank on the national Key Stage 2 test (relative; native mean ~50 in every year) [within-year ranking is INFERENCE: the DP does not state the ranking base in words]",
        score_normalization_quote='"the outcome Y (the percentile score in reading, writing or maths) for pupil i in Year Group 6 of School s" (p. 12); "The percentile reading, writing and Maths score is close to 50 among the population of native English speakers" (p. 11)',
        stakes='high-stakes for the school: "The tests are fairly high stakes for the school because they form the basis of \'School Performance Tables\'" (p. 8)',
        comparison="within school across adjacent cohorts (Year 6 year groups); IV: Catholic school x post-2004 EU enlargement trend for white non-native share",
        fixed_effects="year dummies; school fixed effects; school-specific time trends; prior attainment at age 7; demographics; time-varying school characteristics; number of non-native speakers; SE clustered on 11,879 schools",
        detects_systemwide_shift="No",
        reason="A percentile rank cannot move when every school moves together, and year dummies plus school fixed effects and trends leave only within-school deviations across cohorts.",
        headline_estimate="Table 4 col. 7 (full spec): reading 0.002 (0.008); writing 0.000 (0.010); maths 0.013 (0.007). Col. 1 (year dummies only): reading -0.120* (0.005). IV maths 1.27 (0.69), p<0.10 (p. 23)",
        estimate_unit="KS2 percentile points per 1 pp of non-native English speakers in the year group",
        source_url="https://docs.iza.org/dp6451.pdf",
        source_locator="stakes p. 8; eq. (1) p. 12; Table 4 p. 32 (printed)",
        quote='"Controls are included for year dummies (Dt) ... school fixed effects (µ) which are allowed to vary with a time trend." (p. 12); "leaving only idiosyncratic variation in the percentage of non-native English speakers within the same school across cohorts" (p. 5)',
    ),
    dict(
        study="Ballatore, Fort & Ichino 2018",
        citation="Ballatore R.M., Fort M., Ichino A. (2018), Tower of Babel in the classroom: immigrants and natives in Italian schools, Journal of Labor Economics 36(4):885-921; read as authors' accepted version dated 22 Feb 2018",
        country="Italy, grades 2 and 5, INVALSI 2009-10 (one cross-section, census of schools)",
        outcome_measure="percent correct on a national test (INVALSI fraction of correct answers, school-grade mean of natives), single year",
        score_normalization_quote='"We measure school performance with the fraction of correct answers in each test." (p. 7); effect sizes are expressed in the school-level SD of that fraction (Table 1)',
        stakes="low-stakes for pupils and schools in 2009-10 [TRAINING-DATA]; the paper tests teacher score manipulation (sec. 5.6, Angrist et al. 2017a cheating indicator)",
        comparison="within school-grade class formation rules (Maimonides x Feb/Sept enrolment IV), identified between schools within the same institution (principal)",
        fixed_effects="institution x grade fixed effects; 2nd-order polynomial in native enrolment at school x grade; school-level family controls; SE clustered at institution-grade",
        detects_systemwide_shift="No",
        reason="One cross-section with institution x grade effects compares schools under the same principal on a raw percent-correct test, so a level common to all Italian schools is absorbed by the fixed effects and cannot be separated from test difficulty.",
        headline_estimate="Language, grades pooled, Pure Ethnic Composition effect delta = -0.0158** (0.0077) two-endogenous (first-stage F immigrants 2.93); -0.0085*** (0.0025) one-endogenous (F 18.0); 'roughly 16% of a standard deviation' / 'about 9%'",
        estimate_unit="fraction correct (0-1) per native replaced by one immigrant at constant class size; SD is the school-level SD (0.10 language)",
        source_url="https://www.andreaichino.it/wp-content/uploads/2019/02/ichino_ballatore_fort.pdf",
        source_locator="data p. 5-7 (pdf pages); eq. (5) and FE p. 12; Table 2 p. 27 (pdf page)",
        quote='"We aggregate the data at the school level since the variation we exploit for identification is between schools managed by the same principal." (p. 5); "ηkg denotes institution×grade fixed effects" (p. 12)',
    ),
    dict(
        study="Tonello 2016",
        citation="Tonello M. (2016), Peer effects of non-native students on natives' educational outcomes: mechanisms and evidence, Empirical Economics 51(1):383-414 (doi 10.1007/s00181-015-0995-y); read as precursor IEB WP 2011/21 'Mechanisms of peer interactions between native and non-native students: rejection or integration?'",
        country="Italy, grade 8, INVALSI First Cycle final exam, 2007-08 to 2009-10, census (~500,000 pupils per wave)",
        outcome_measure="percent correct on a national test (INVALSI First Cycle exam), entered as log of the school mean for natives; not linked across years",
        score_normalization_quote='"The dependent variable is the log of the Invalsi IC school mean test score for native students" (WP p. 17)',
        stakes="high-stakes for pupils: the test is part of the lower-secondary final state exam ('school years final exams', WP p. 14) [INFERENCE; TRAINING-DATA that it counted toward the diploma grade]; the WP uses a school cheating-decile dummy in a robustness table",
        comparison="within school across adjacent cohorts (school-level aggregation)",
        fixed_effects="school fixed effects; territorial (5 macro-areas) x year fixed effects; catchment-area census controls; class and school controls",
        detects_systemwide_shift="No",
        reason="Territory-by-year effects absorb any national or macro-regional shift in each year and school effects absorb levels, so only a school's cohort-to-cohort deviation in share is used, on a test not linked across years.",
        headline_estimate="Table 5 col. III (all controls): Language -0.0653** (0.0253); Maths col. VI -0.0499 (0.0344). Per 10 pp: -0.65% of native school-mean language score [CALCULATION]. WP text says '1% -> 6.5%', a units slip",
        estimate_unit="log points of native school-mean score per unit (0-1) non-native school share",
        source_url="https://ieb.ub.edu/wp-content/uploads/2018/04/2011-IEB-WorkingPaper-21.pdf",
        source_locator="design WP p. 4; FE footnote 13 p. 11; data p. 14; Table 5 p. 27 (printed); sorting check p. 21",
        quote='"designed to control for across school sorting through school fixed-effects, territorial by year fixed effects and school specific catchment-area socio economic variables" (WP sec. 7.2, p. 21); "exploits the within school idiosyncratic variation in non-native share between adjacent cohorts" (p. 4)',
    ),
    dict(
        study="Frattini & Meschi 2019",
        citation="Frattini T., Meschi E. (2019), The effect of immigrant peers in vocational schools, European Economic Review 113:1-22 (doi 10.1016/j.euroecorev.2018.12.005); read as IZA DP 11027 (Sep 2017)",
        country="Italy, Lombardy regional vocational training, cohorts entering 2009 and 2010 (14,700 pupils, 1,308 classes)",
        outcome_measure="regional test standardized within wave (z-score), value-added on the entrance test",
        score_normalization_quote='"standardized to have a mean of zero and a standard deviation of one in each wave" (p. 7); "Yicst is the outcome (standardized test scores in either maths or literacy)" (p. 8)',
        stakes='high-stakes for pupils: "standardized, externally marked (graded) tests ... at the end of the third year as part of the final exam" (p. 6)',
        comparison="within school across classes and adjacent cohorts",
        fixed_effects="school fixed effects; cohort dummy; standardized entrance scores; age, gender, class size, share female; SE clustered by class",
        detects_systemwide_shift="No",
        reason="Scores are z-scored within each wave and school effects plus a cohort dummy absorb levels, so a region-wide fall in vocational-school standards leaves the outcome unchanged.",
        headline_estimate="Table 5.1: maths -0.463** (0.203) full sample, low-ability -0.754*** (0.235), high-ability -0.392 (0.257); literacy 0.131 (0.164). Per 10 pp maths -0.046 SD [CALCULATION; text: 'about a 4.6% of a standard deviation decrease', p. 13]",
        estimate_unit="within-wave SD of natives' end-of-course score per unit (0-1) class immigrant (foreign-born) share",
        source_url="https://docs.iza.org/dp11027.pdf",
        source_locator="data p. 6-7; identification p. 8; Table 5.1 (pdf p. 37, printed p. 35)",
        quote='"Our identification strategy relies on the random variation of students across both classes and adjacent cohorts within schools." (p. 8)',
    ),
    dict(
        study="Jensen & Rasmussen 2011",
        citation="Jensen P., Rasmussen A.W. (2011), The effect of immigrant concentration in schools on native and immigrant children's reading and math skills, Economics of Education Review 30(6):1503-1515 (doi 10.1016/j.econedurev.2011.08.002); journal text UNREACHABLE; read as precursor WP Jensen & Wuertz (Apr 2008), 'Immigrant and Native Children's Cognitive Outcomes and the Effect of Ethnic Concentration in Danish Schools'",
        country="Denmark, age 15, PISA 2000 pooled with the 2005 PISA-Ethnic immigrant oversample, register-linked",
        outcome_measure="fixed absolute international scale (PISA reading, WLE score on the OECD metric); journal version adds maths [journal UNVERIFIED]",
        score_normalization_quote='"OECD has standardized the mean score across all OECD countries participating in PISA-2000 to 500 with a standard deviation of 100." (2008 WP p. 9); WLE score used rather than plausible values (fn.)',
        stakes="low-stakes (PISA survey) [TRAINING-DATA: not discussed]",
        comparison="across schools within country (cross-section; IV = county-level ethnic concentration, i.e. between counties within Denmark); school-FE variant also run",
        fixed_effects="none in OLS/IV beyond family and school controls; school fixed effects in a robustness model (2008 WP Tables 5, 13)",
        detects_systemwide_shift="No",
        reason="The scale is absolute but all variation is between Danish schools (or counties, through the IV) at essentially one point in time, so a level common to every Danish school has no comparison group.",
        headline_estimate="2008 WP, native Danish children only, reading: OLS Model 3 -0.28** (Table 9), IV -0.31* (Table 11); SEs not printed (stars only). Journal native maths/reading estimates [UNVERIFIED: journal paywalled]; abstract says effect is stronger for natives and for maths",
        estimate_unit="PISA reading points (OECD SD 100) per 1 pp of non-Western share in the school",
        source_url="https://pure.au.dk/ws/files/2953/immigrant_children_wp.pdf (WP); journal https://doi.org/10.1016/j.econedurev.2011.08.002 (not read)",
        source_locator="2008 WP: scale p. 9; IV p. 8 and sec. 5.2; Table 9 (pdf p. 30); Table 11 (pdf p. 32)",
        quote='"The instrument follows Dustmann and Preston (2001) in using ethnic concentration in a larger geographical area as an instrument for local ethnic concentration." (2008 WP p. 8)',
    ),
    dict(
        study="Schilling & Hoeckel 2026 (Hamburg)",
        citation="Schilling P., Hoeckel L.S. (2026), Starting off on the right foot: language learning classes and the educational success of refugee children, Economic Journal 136(676):1217-1253 (doi 10.1093/ej/ueaf087); read as published version from KOPS (Konstanz repository); native-spillover section 5",
        country="Germany (Hamburg city-state), German-born pupils, grade 5 KERMIT, school-starting cohorts 2011-2015",
        outcome_measure="state test (Hamburg KERMIT grade 5) standardized pooled over all years (z-score), with test-year fixed effects",
        score_normalization_quote='"We standardise the scores to have a mean of 0 and an SD of 1 across all years and students." (p. 1228-1229)',
        stakes='low-stakes diagnostic: KERMIT 5 "is designed to give teachers at the new secondary school objective information about the educational needs of their students" (p. 1224), administered by external test conductors',
        comparison="within school across cohorts (cumulative grade 1-4 refugee share of the pupil's first primary school)",
        fixed_effects="first-primary-school fixed effects; test-year fixed effects; first-grade fixed effects; individual controls; time-varying school controls (children per school-year-grade, social index, student-teacher ratio); SE clustered by first school",
        detects_systemwide_shift="No",
        reason="Although the z-score is pooled across years, test-year fixed effects absorb any Hamburg-wide change in a given year and school effects absorb levels, leaving only within-school cohort variation in refugee share (residual SD 0.016).",
        headline_estimate="Table 10 panel B col. 4: share of refugee students (cohort) 0.27 (0.58); raw col. 1 -4.39*** (1.35); with individual controls -2.10*** (0.73). N = 28,125 German-born pupils",
        estimate_unit="SD of pooled KERMIT score per unit (0-1) cumulative refugee share",
        source_url="https://kops.uni-konstanz.de/server/api/core/bitstreams/51558be8-5fd1-4f21-8f45-ddba2a632b7e/content (journal: https://academic.oup.com/ej/article/136/676/1217/8249266)",
        source_locator="KERMIT p. 1223-1224; standardization p. 1228-1229; eq. (1) p. 1244; Table 10 p. 1246 (journal pages)",
        quote='"By including these fixed effects, we exploit variation in preparatory class availability and refugee composition of students across different cohorts within each primary school." (p. 1244)',
    ),
    dict(
        study="Hassan, Hvidtfeldt, Andersen & Udsen 2023 (Denmark refugees)",
        citation="Hassan S., Hvidtfeldt C., Andersen L.H., Udsen R.O. (2023), Do refugee children impair the academic performance of native children in the school? Informative null results from Danish register data, European Sociological Review 39(3):352ff (doi 10.1093/esr/jcac059); read as OUP advance-article PDF (pp. 1-14) hosted by the Rockwool Foundation",
        country="Denmark, public schools, school cohorts 2007/2008-2015; Danish national tests (Danish grades 2 and 4; maths grades 3 and 6)",
        outcome_measure="national test standardized within grade-year (z-score), averaged over three profile areas and re-standardized",
        score_normalization_quote='"we standardise the test scores (within grade-year) from each profile area separately ... We then average the test scores for each student across the three profile areas and standardise the average once again" (p. 6)',
        stakes="low-stakes for pupils (mandatory adaptive IT-based national tests, no grades attached) [TRAINING-DATA]; paper: results 'arguably less affected by potential teacher biases' (p. 6)",
        comparison="within school across cohorts: difference-in-differences in test-score growth (grade 2->4, 3->6) between school cohorts that received a refugee between the two tests and those that did not",
        fixed_effects="school fixed effects; grade (second test) indicator; controls for gender, ethnicity, parental SES measured before age 6, cohort size in both test periods; SE clustered by school; robustness adds calendar-year-by-school and individual fixed effects",
        detects_systemwide_shift="No",
        reason="Scores are re-centred within each grade-year, so a Denmark-wide drop in level leaves every pupil's z-score unchanged, and the contrast is between receiving and non-receiving cohorts in the same school.",
        headline_estimate="Table 3 col. 3 (school FE), Grade x Refugee binary: Danish -0.010 (0.009); maths -0.010 (0.010). Exposure variable col. 6: Danish 0.307 (0.375); maths 0.056 (0.329). Level selection: Refugee col. 1 -0.067*** (0.015) Danish",
        estimate_unit="within grade-year SD; binary = any refugee arrival in the school cohort between the two tests",
        source_url="https://rockwoolfonden.s3.eu-central-1.amazonaws.com/wp-content/uploads/2023/05/Do-refugee-children-impair-the-academic-performance-of-native-children-in-the-school_European-Sociological-Review.pdf (journal: https://academic.oup.com/esr/article/39/3/352/6843667)",
        source_locator="advance-article pagination: standardization p. 6; model p. 7; Table 3 p. 11",
        quote='"a differences-in-differences approach to compare the test score growth of native students who received one or more refugees into their school cohort with that of native students who did not" (Introduction); "µs is a school fixed effect" (p. 7)',
    ),
    dict(
        study="Gould, Lavy & Paserman 2009 (Israel)",
        citation="Gould E.D., Lavy V., Paserman M.D. (2009), Does immigration affect the long-term educational outcomes of natives? Quasi-experimental evidence, Economic Journal 119(540):1243-1269 (doi 10.1111/j.1468-0297.2009.02271.x); read as IZA DP 1883 (Dec 2005); EJ version not read",
        country="Israel, native 5th graders of 1993-94 (one cohort) followed to high school outcomes 1998-2001; 1990s former-USSR and Ethiopian immigration",
        outcome_measure="attainment: dropout before completing 12th grade; passing the high-school matriculation (bagrut) exam; quality of high school attended",
        score_normalization_quote='binary outcomes: "dropping out before completing 12th grade, and passing the matriculation exams" (DP p. 8); no score normalization',
        stakes="high-stakes for pupils: matriculation is 'necessary to attend college' (abstract)",
        comparison="within school across grades: conditional on the school's number of immigrants in grades 4-6, the share landing in grade 5 is treated as random; stratified OLS/IV within cells, instrument = predicted share from immigrants' birth dates",
        fixed_effects="no school FE (one cohort: 'This prevents us from using a traditional identification strategy based on multiple cohorts and school fixed effects', fn. 4); stratification cells on predicted immigrants in grades 4-6; controls for predicted grade-5 size and immigrants, squares and interaction; parental schooling, 1991 school test scores, SES index; SE clustered by school",
        detects_systemwide_shift="No",
        reason="The outcome is a national pass threshold, but with one national cohort and comparison only among schools with the same number of immigrants in grades 4-6, anything common to all Israeli schools (including a change in the bagrut standard) has no counterfactual.",
        headline_estimate="Table 7 panel B (with controls), weighted average of stratified IV: passed matriculation -0.0028 (t = -2.00); dropped out 0.0015 (t = 2.51). Text: 0 -> 10% immigrants in grade 5 reduces matriculation by 3.16 pp (p. 26)",
        estimate_unit="probability (0-1) per 1 pp of immigrants in the grade-5 cohort; robust t-statistics in brackets (SE ~0.0014 [CALCULATION])",
        source_url="https://docs.iza.org/dp1883.pdf",
        source_locator="abstract (pdf p. 3); fn. 4 p. 8; Table 7 p. 38; decomposition p. 26 (printed pages)",
        quote='"We control for the endogeneity of immigrant placement across schools by conditioning on the total number of immigrants in a school and exploit random variation in the number of immigrants across grades within the same school." (abstract)',
    ),
    dict(
        study="Tumen 2021 (Turkey, Syrian refugees; search (a) find)",
        citation="Tumen S. (2021), The effect of refugees on native adolescents' test scores: quasi-experimental evidence from PISA, Journal of Development Economics 150:102633; read as IZA DP 14039 (2021)",
        country="Turkey, 15-year-olds, PISA 2009/2012 (pre) vs 2015/2018 (post), 12 NUTS1 regions",
        outcome_measure="fixed absolute international scale (PISA), entered as 'standardized value of the corresponding test score' [standardization base not stated]",
        score_normalization_quote='"Following the convention in the literature, the standardized values of the test scores are used in the regressions." (DP p. 13)',
        stakes="low-stakes (PISA survey) [TRAINING-DATA]",
        comparison="between regions within one country over time (difference-in-differences of high- vs low-refugee NUTS1 regions, pre/post 2015; IV with distance to border crossings)",
        fixed_effects="region fixed effects; year fixed effects; grade and month-of-birth FE; parental education; regional GDP per capita and Syria trade; SE clustered by region (3-12 clusters) with wild-bootstrap p-values",
        detects_systemwide_shift="Partly",
        reason="It can see a shift common to all schools in a high-refugee region relative to other regions, but year fixed effects absorb anything common to all of Turkey (national curriculum, exams, standards), and refugee children were mostly not yet in regular schools before 2016, so it isolates a labour-market channel rather than a school channel.",
        headline_estimate="Table 4 panel A (2009-2015), specification III: maths 0.111** (0.042); science 0.159* (0.069); reading 0.139** (0.059). Panel B (2009-2018) spec. III: maths 0.101 (0.072); reading 0.104 (0.079)",
        estimate_unit="SD of PISA score, treated vs control regions after vs before the influx (binary treatment)",
        source_url="https://docs.iza.org/dp14039.pdf",
        source_locator="eq. (1) p. 11; standardization p. 13; Table 4 (pdf p. 35)",
        quote='"fr and ft are region and year fixed effects, respectively" (DP p. 11); design exploits "the time variation in regional refugee intensity" (abstract)',
    ),
]


def main() -> None:
    out = Path(__file__).with_name("design_eu.csv")
    with out.open("w", encoding="utf-8", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=COLS, lineterminator="\n")
        w.writeheader()
        for r in ROWS:
            missing = set(COLS) - set(r)
            if missing:
                raise SystemExit(f"row {r.get('study')} missing {sorted(missing)}")
            w.writerow(r)
    print(f"wrote {len(ROWS)} rows to {out}")


if __name__ == "__main__":
    main()
