"""Write design_us.csv from rows verified against primary text (see NOTES_us.md).

Run from the repository root:
    OPENBLAS_NUM_THREADS=1 uv run --no-project python3 \
        infra/immigration-fiscal/school_systemwide_2026_09_27/design_table/build_design_us.py
"""
import csv
from pathlib import Path

OUT = Path(__file__).with_name("design_us.csv")
COLS = [
    "study", "citation", "country", "outcome_measure", "score_normalization_quote", "stakes",
    "comparison", "fixed_effects", "detects_statewide_shift", "reason", "headline_estimate",
    "estimate_unit", "source_url", "source_locator", "quote",
]

ROWS = [
    dict(
        study="Figlio, Giuliano, Ozek & Sapienza 2024",
        citation="Diversity in Schools: Immigrants and the Educational Performance of U.S.-Born Students. Review of Economic Studies 91(2):972-1006 (NBER w28596)",
        country="US (Florida)",
        outcome_measure="state accountability test standardized within grade-year (z-score): FCAT math and reading, grades 3-10, 2002-03 to 2011-12",
        score_normalization_quote="\"we standardize the statewide test scores to zero mean and unit variance at the grade-year level over the entire population of students\" (p. 977, s.2.4); fn 12 p. 984: robustness standardizes within the US-born sample",
        stakes="high-stakes for the school (FCAT drives Florida A-F school grades) [TRAINING-DATA: the paper does not discuss stakes]",
        comparison="within family (siblings); siblings in different grades of the same school over time or in different schools",
        fixed_effects="grade x year; school x year; family; family x year (preferred col. 5)",
        detects_statewide_shift="No",
        reason="Scores are re-centred to mean zero in every Florida grade-year and school x year FE absorb anything common to a school-year, so a shift common to all Florida schools is removed twice.",
        headline_estimate="All US-born, col.5: math 0.224 (SE 0.074), reading 0.108 (SE 0.064) per unit exposure share = +0.0224/+0.0108 SD per +10pp [CALCULATION]; 10th->90th pct exposure (1%->13%): +2.8%/+1.7% SD. White pupils col.5: math 0.128 (0.107), reading -0.007 (0.099) per unit share",
        estimate_unit="SD of grade-year-standardized FCAT per unit (0-1) cumulative foreign-born cohort share",
        source_url="https://www.anderson.ucla.edu/sites/default/files/document/2025-06/diversityinschools.pdf",
        source_locator="Table 4 p. 985 (all US-born); Table 5 p. 988 (White); eq. 2 p. 984; text p. 986-987",
        quote="\"Our identification relies on the comparison between siblings in the same year, based on their 'historic' exposure\" (p. 986); Table 4 note: \"test scores ... standardized by year and grade\" (p. 985)",
    ),
    dict(
        study="Diette & Oyelere 2017 (IZA J. Migration)",
        citation="Gender and racial differences in peer effects of limited English students: a story of language or ethnicity? IZA Journal of Migration 6:2",
        country="US (North Carolina)",
        outcome_measure="state accountability test standardized within grade-year (z-score): NC End-of-Grade math and reading, grades 4-8, 1998-2006; value-added with lagged z-score",
        score_normalization_quote="\"The z-scores were calculated using the entire student population who took the exams within the grade in that particular year.\" (fn 14)",
        stakes="high-stakes for the school (NC ABCs accountability) [TRAINING-DATA: not discussed in the paper]",
        comparison="within school across grades in the same year",
        fixed_effects="school x year; grade; year; SEs clustered school-grade-year",
        detects_statewide_shift="No",
        reason="Identification is across grades inside one school-year and the outcome is re-standardized within each statewide grade-year, so a statewide level shift cannot load on the LE-share coefficient.",
        headline_estimate="White, panel C (with Latino share): math LE share -0.035 (SE 0.078), reading -0.002 (0.052); largest, Black reading -0.128 (0.057) = -0.013 SD per +10pp",
        estimate_unit="SD of grade-year z-score per unit (0-1) LE share of the student's grade in the school",
        source_url="https://link.springer.com/article/10.1186/s40176-016-0074-y",
        source_locator="Table 4 p. 10; eq. 1 p. 7; fn 14",
        quote="\"potential endogeneity is overcome by identifying impacts across grades at a particular point in time\" (p. 7-8)",
    ),
    dict(
        study="Diette & Oyelere 2014 (AER P&P), via IZA DP 7856",
        citation="Gender and Race Heterogeneity: The Impact of Students with Limited English on Native Students' Performance. AER 104(5):412-17; working paper IZA DP 7856 (Dec 2013)",
        country="US (North Carolina)",
        outcome_measure="state accountability test standardized within grade-year (z-score): NC End-of-Grade math and reading",
        score_normalization_quote="\"The z-scores were calculated using the entire student population who took the exams within the grade in that particular year.\" (DP fn 6)",
        stakes="high-stakes for the school [TRAINING-DATA]",
        comparison="within school across grades in the same year (preferred); school FE and OLS also reported",
        fixed_effects="school x year (preferred); school FE alternative; grade and year FE",
        detects_statewide_shift="No",
        reason="Same as the 2017 paper: across-grade contrasts inside a school-year on grade-year-standardized scores.",
        headline_estimate="School x year FE: male math -0.0742 (SE 0.034), male reading -0.0719 (0.038); female math -0.0248 (0.033), reading -0.0412 (0.036); +1pp LE share -> male math -0.00074 SD. [DP numbers; AER P&P printed tables not reached]",
        estimate_unit="SD of grade-year z-score per unit (0-1) LE share",
        source_url="https://docs.iza.org/dp7856.pdf",
        source_locator="DP Table 6 p. 28; text p. 11 and p. 14",
        quote="\"endogeneity is overcome by identifying impacts across grades within a particular point in time\" (DP p. 11)",
    ),
    dict(
        study="Diette & Oyelere 2017 (Education Economics), via IZA DP 6561",
        citation="Do limited English students jeopardize the education of other students? Lessons from the North Carolina public school system. Education Economics 25(5):446-461; working paper IZA DP 6561 (2012)",
        country="US (North Carolina)",
        outcome_measure="state accountability test standardized within grade-year (z-score): NC End-of-Grade math and reading, grades 4-8, 1999-2006 [normalization INFERENCE from sister papers on the same data]",
        score_normalization_quote="DP prints no normalization sentence; eq. 1 p. 20 uses the \"Z score in math or English\"; achievement groups are \"test performance quartile within their grade in the state in a given year\" (p. 8)",
        stakes="high-stakes for the school [TRAINING-DATA]",
        comparison="within school across grades in the same year (preferred); within school-grade over time; within student over time",
        fixed_effects="school x year (preferred); school x grade; individual FE; year and grade FE",
        detects_statewide_shift="No",
        reason="The preferred model absorbs every school-year; the alternatives keep year FE, and the outcome is a within-grade-year z-score, so no specification can see a statewide level shift.",
        headline_estimate="School x year FE: math -0.0516 (SE 0.024), reading -0.0579 (0.026); top quartile math -0.0823 (0.04), reading -0.0780 (0.03); school x grade FE math +0.0572 (0.014)",
        estimate_unit="SD of z-score per unit (0-1) LE share",
        source_url="https://docs.iza.org/dp6561.pdf",
        source_locator="DP Table 5 and Table 6; text p. 22. Published Education Economics tables not reached",
        quote="\"When school by year fixed effects are introduced, we are identify effects within a school across grades at a specific period of time.\" (DP p. 22)",
    ),
    dict(
        study="Hunt 2017",
        citation="The Impact of Immigration on the Educational Attainment of Natives. Journal of Human Resources 52(4):1060; working paper NBER w18047 (2012)",
        country="US (all states)",
        outcome_measure="attainment: share of natives aged 21-27 who completed 12 years of schooling (census 1950-2000, ACS 2008-10), GED-corrected, adjusted for age/sex (and race/ethnicity) in a first step",
        score_normalization_quote="n/a (no test score). GEDs: \"I therefore correct the 12-year completion rates using annual published tables on GEDs\" (WP p. 7)",
        stakes="n/a: credential count; a statewide easing of diploma requirements would raise it mechanically [INFERENCE]",
        comparison="between states over time (state panel, 10-year differences; 2SLS with 1940 settlement shift-share instrument)",
        fixed_effects="state; year; BEA region x year trends; 1940-covariate x year trends; SEs clustered by state",
        detects_statewide_shift="Partly",
        reason="State-specific changes correlated with immigration identify the estimate, so a statewide shift is inside the design, but the outcome is a credential count that a lowered standard would raise rather than lower, and year and region-by-year terms absorb common shifts.",
        headline_estimate="2SLS: all natives 0.34 (SE 0.11) pp per 1pp immigrant share of population 11-64 (abstract: 0.3); non-Hispanic white 0.21 (0.11); Black 0.36 (0.14); Hispanic -0.22 (0.24)",
        estimate_unit="percentage points of 12-year completion per 1pp immigrant share",
        source_url="https://www.nber.org/system/files/working_papers/w18047/w18047.pdf",
        source_locator="WP Table 2 col. 7 and Table 3 col. 7 (p. 37-38); eq. 2-3 p. 10-11. JHR printed tables not reached",
        quote="\"Using a state panel based on census data from 1940-2010, I examine the impact of immigration on the high school completion of natives\" (abstract); \"All specifications include year dummies; fixed effects specifications also include state dummies\" (Table 2 note)",
    ),
    dict(
        study="Figlio & Ozek 2019 (Haiti earthquake)",
        citation="Unwelcome Guests? The Effects of Refugees on the Educational Outcomes of Incumbent Students. Journal of Labor Economics 37(4); working paper CALDER WP 181 (Jan 2018)",
        country="US (Florida)",
        outcome_measure="state accountability test standardized within grade-year (z-score): FCAT reading and math, Spring 2010, 2010-11, 2011-12; also discipline, mobility",
        score_normalization_quote="\"test scores in reading and math standardized to zero mean and unit variance at the grade-year level\" (WP p. 7)",
        stakes="high-stakes for the school (FCAT) [TRAINING-DATA]",
        comparison="within school across grades (Spring 2010 school-grade refugee share); IV on refugee age distribution; family FE robustness",
        fixed_effects="school; grade (of Spring 2010 placement); SEs clustered by school; family FE and student FE in appendix checks",
        detects_statewide_shift="No",
        reason="Each outcome year is one statewide cross-section standardized within grade-year and school FE leave only across-grade contrasts inside a school, so a Florida-wide shift is invisible.",
        headline_estimate="Spring 2010, school FE + covariates: top receiving schools reading 0.006 (SE 0.004), math 0.003 (0.005); all receiving schools reading 0.002 (0.003), math 0.001 (0.004)",
        estimate_unit="SD per 1pp refugee share of the school-grade",
        source_url="https://caldercenter.org/sites/default/files/2024-11/WP%20180_0.pdf",
        source_locator="WP Table 5 col. III (p. 27); eq. 1 p. 6; text p. 12. JOLE printed tables not reached",
        quote="\"we rely on within-school, across-grade variation in refugee concentration to study the effects of the refugee influx on incumbent students\" (WP p. 6)",
    ),
    dict(
        study="Doan, Morales, Ozek & Schwartz 2024 (Delaware new ELs)",
        citation="Educational Spillover Effects of New English Learners in a New Destination State. Educational Evaluation and Policy Analysis 2024; working paper EdWorkingPaper 23-818 (Aug 2023)",
        country="US (Delaware)",
        outcome_measure="state accountability test standardized within grade-year (z-score): Smarter Balanced ELA and math, 2015-16 to 2018-19 (vertical scale discarded by re-standardization)",
        score_normalization_quote="\"test scores standardized to zero mean and unit variance at the year-grade level\" (WP p. 10, eq. 1)",
        stakes="high-stakes for the school (SBAC is Delaware's accountability test) [TRAINING-DATA]",
        comparison="within school across grades in the same year",
        fixed_effects="school x year; grade; prior-year scores; SEs clustered school-grade-year",
        detects_statewide_shift="No",
        reason="School x year FE plus year-grade standardization remove any Delaware-wide shift; only the new-EL share of one grade relative to other grades in the same school-year is used.",
        headline_estimate="All existing students ELA 0.008 (SE 0.004), math 0.003 (0.004); never-EL ELA 0.005 (0.003), math -0.000 (0.003)",
        estimate_unit="SD per 1pp new-EL share of the school-grade",
        source_url="https://edworkingpapers.com/sites/default/files/ai23-818.pdf",
        source_locator="WP Table 2 col. III (p. 22); eq. 1 p. 10. EEPA printed tables not reached",
        quote="\"it requires sufficient cross-grade variation in new EL student share within schools\" (WP p. 10)",
    ),
    dict(
        study="Borgschulte, Cho, Lubotsky & Rothbaum 2025",
        citation="Immigration and Inequality in the Next Generation. NBER Working Paper 33961 (June 2025)",
        country="US (214 commuting zones)",
        outcome_measure="adult outcomes: W-2 income rank in the national distribution (cohorts born 1977-85); also attainment (high school, BA completion)",
        score_normalization_quote="n/a (no test score). Ranks are national: \"Child and parental income ranks reflect their standing within the national distribution.\" (p. 22)",
        stakes="n/a (tax-record earnings are not produced by schools; HS completion is a credential)",
        comparison="across cities/metros (commuting zones), 1980-90 immigrant inflow, shift-share enclave IV; CZ-FE robustness by parental-income decile",
        fixed_effects="none in the primary cross-section (1980 CZ controls + 1940 mobility controls, SEs clustered by CZ); CZ-of-birth FE in the robustness model",
        detects_statewide_shift="Partly",
        reason="The primary model uses cross-CZ variation with no state FE and a nationally ranked earnings outcome, so a state- or city-wide learning loss that lowered adult earnings would load on the estimate, but it cannot separate a school channel from labour-market channels and the HS-completion outcome would move the wrong way under lowered standards.",
        headline_estimate="Income rank per 1pp inflow: decile 1 +0.147 (SE 0.080), decile 10 -0.238 (0.076) (= +1.5 / -2.4 rank points per 10pp); BA completion decile 10 -0.593 pp per 1pp (Table 5 col. 6)",
        estimate_unit="national income-rank percentile points (or pp of completion) per 1pp CZ immigrant inflow 1980-90 relative to 1980 population",
        source_url="https://www.nber.org/system/files/working_papers/w33961/w33961.pdf",
        source_locator="Table 1 col. 1 (p. 54); Table 5 col. 6 (p. 58); eq. 1 p. 12; text p. 21-22",
        quote="\"We estimate the causal impacts of immigration to U.S. cities on the intergenerational economic mobility of children of U.S.-born parents.\" (abstract); \"Standard errors are clustered at the CZ-level.\" (p. 13)",
    ),
    dict(
        study="Cho 2011 (PAA manuscript; published EER 2012)",
        citation="Are there Peer Effects Associated with Having English Language Learner (ELL) Classmates? Evidence from the ECLS-K. PAA 2011 paper 110005 (published Economics of Education Review 2012, not reached)",
        country="US (national sample, ECLS-K 1998 cohort)",
        outcome_measure="fixed absolute scale re-standardized per wave: ECLS-K reading and math IRT scale scores, spring K and spring 1st grade, converted to mean 0 / SD 1 per test and wave over the national sample",
        score_normalization_quote="\"the test scores are transformed to have mean 0 and standard deviation 1 for the overall sample on each of the tests and time periods\" (p. 12)",
        stakes="low-stakes (federal survey assessment, no consequences for schools) [INFERENCE from survey design]",
        comparison="within school across classrooms (school FE); within child across K and 1st grade (child FE); child FE + school FE preferred",
        fixed_effects="school; child; child + school; SEs account for classroom clustering",
        detects_statewide_shift="No",
        reason="The exposure is a classroom dummy compared across classrooms of one school and across two waves for one child, so exposed and unexposed children share any statewide shift, and per-wave standardization removes the national level.",
        headline_estimate="Child FE + school FE, reading: all -0.042 (SE 0.019); non-Hispanic white -0.037 (0.023); school FE only: reading -0.052 (0.017), math -0.039 (0.017)",
        estimate_unit="SD (per-wave national standardization) for having any ELL classmate vs none",
        source_url="https://paa2011.populationassociation.org/papers/110005",
        source_locator="Table 5 (p. 39); Table 2 (p. 33); Table 3 (p. 36); text p. 12, 15",
        quote="\"θ is identified by the difference in the chance of having any ELL classmates between kindergarten and first grade\" (p. 15)",
    ),
    dict(
        study="Repo ECLS-K peer checks 2026-09-20",
        citation="research/immigration-school-peer-checks-2026-09-20.md; lane infra/immigration-fiscal/school_peer_checks_2026_09_20",
        country="US (national sample, ECLS-K 1998 cohort; non-Hispanic white, US-born, English-home children)",
        outcome_measure="fixed absolute scale re-standardized per wave: ECLS-K IRT scale fields, standardized within each wave with that wave's child weights across all origins",
        score_normalization_quote="\"Outcomes use the correct IRT scale fields, standardized separately in each wave using that wave's positive child weights across all origins.\" (lane README)",
        stakes="low-stakes (federal survey assessment)",
        comparison="within school across classrooms",
        fixed_effects="school; cubic baseline reading and math; CR1 school-cluster SEs",
        detects_statewide_shift="No",
        reason="School FE compare classrooms inside one school, so anything common to a school, district or state cancels; per-wave standardization removes the national level.",
        headline_estimate="Any LEP classmate, school FE: spring 2000 reading -0.040 [95% -0.111, +0.031], math -0.056 [-0.136, +0.024]; kindergarten reading +0.004 [-0.056, +0.065], math -0.026 [-0.085, +0.033]",
        estimate_unit="SD (per-wave weighted standardization) for any LEP classmate vs none",
        source_url="research/immigration-school-peer-checks-2026-09-20.md",
        source_locator="memo table 'Any LEP classmate versus none'; lane derived/results.json; README",
        quote="\"School fixed effects compare classrooms within a school.\" (lane README); memo: \"Within-school comparisons remove common school conditions and cannot recover the full schoolwide resource effect.\"",
    ),
    dict(
        study="Ahn & Jepsen 2015",
        citation="The effect of sharing a mother tongue with peers: evidence from North Carolina middle schools. IZA Journal of Migration 4:5",
        country="US (North Carolina)",
        outcome_measure="state accountability test standardized (mean zero; level of standardization not stated): NC End-of-Grade reading and math, grades 6-8, 2006-2012, value-added",
        score_normalization_quote="\"The dependent variable is a standardized test score in either reading or mathematics\" (p. 9); \"test scores are standardized with mean zero\" (p. 13). Grade-year level [UNVERIFIED]",
        stakes="high-stakes for school and student, stated by the paper: \"the exams are high-stakes not only for the school, but for the students as well\" (p. 6)",
        comparison="within student over time (changes in grade-level % LEP peers), net of school FE",
        fixed_effects="student; school; grade x year; SEs clustered school-grade-year",
        detects_statewide_shift="No",
        reason="Grade-by-year FE absorb everything common to all North Carolina students in a grade-year and scores are mean-zero standardized, so a statewide shift cannot load on % LEP.",
        headline_estimate="Non-LEP students, spec NL1: reading % LEP -0.106 (SE 0.042); math -0.073 (0.056) = -0.00106 SD per 1pp, -0.0106 SD per +10pp [CALCULATION from the paper's own reading]",
        estimate_unit="percent of an SD per 1pp LEP share of the grade (paper p. 11-12)",
        source_url="https://link.springer.com/article/10.1186/s40176-015-0030-2",
        source_locator="Table 2 NL1 (p. 12); Table 3 NL1 (p. 13); eq. 1 p. 9; data p. 6",
        quote="\"The model includes student fixed effects (ω), school fixed effects (ρ), and grade-specific time fixed effects (τ)\" (p. 9)",
    ),
    dict(
        study="Betts & Fairlie 2003 (native flight)",
        citation="Does immigration induce 'native flight' from public schools into private schools? Journal of Public Economics 87:987-1012",
        country="US (132 metropolitan areas)",
        outcome_measure="private-school enrollment of native-born children (not achievement), 1980 and 1990 census microdata",
        score_normalization_quote="n/a (no test score; outcome is the probability of attending private school)",
        stakes="n/a",
        comparison="across cities/metros: 1980-90 changes across 132 MAs (MA fixed effects via first differences); IV specification",
        fixed_effects="metropolitan-area FE (first-difference); no state FE",
        detects_statewide_shift="Partly",
        reason="Identification uses between-MA changes with no state FE, so it sees a behavioural response to whatever changed in a metro's public schools, including a state policy shift, but it measures enrollment choices, not learning.",
        headline_estimate="Secondary school, GLS: immigrant share 1.7766 (SE 0.8514), scaled derivative 0.2594 = 0.26 natives switch to private per immigrant added to public schools; OLS 0.2248; IV 3.9049 (2.3059), scaled 0.5702; primary school: no significant relation",
        estimate_unit="natives moving to private school per immigrant added to public schools (scaled probit derivative)",
        source_url="https://people.ucsc.edu/~rfairlie/papers/published/jpube%202003%20-%20native%20flight.pdf",
        source_locator="Table 2 (p. 1000-1001); eq. 3.1-3.2 p. 997; text p. 1001",
        quote="\"The analysis uses 1980 and 1990 Census data from 132 metropolitan areas.\" (abstract); \"Each immigrant added to the public schools in an MA results in a predicted decrease of 0.26 native students in public schools\"",
    ),

    dict(
        study="Hooper, Shipan, Bamat & Bohrnstedt 2024 (NAEP Validity Studies panel, AIR) [search find]",
        citation="Study of Changes in Public School Composition During the Pandemic and Their Relationship With NAEP Performance. NAEP Validity Studies Panel / AIR, September 2024",
        country="US (nation, states, TUDA districts)",
        outcome_measure="fixed absolute scale comparable over time: NAEP grade 8 mathematics scale scores, 2019 vs 2022 (public schools)",
        score_normalization_quote="n/a: NAEP scale points; Beaton-Chromy partition of the 2019-2022 change into \"the performance effect\" and \"the population effect, reflecting the gain or loss caused by changes in population\" (method section)",
        stakes="low-stakes (NAEP)",
        comparison="between states (and districts) over time, 2019 to 2022, as a decomposition of each state's mean change; no causal model of EL share on non-EL scores",
        fixed_effects="none (partitioning and propensity reweighting of the 2022 sample to 2019 characteristics)",
        detects_statewide_shift="Partly",
        reason="The measure is absolute, low-stakes and compared across states over time, so a statewide shift is visible in the performance effect, but the design only books the mechanical composition component to EL growth and does not test whether EL growth lowered other students' scores.",
        headline_estimate="National: EL population change accounts for nearly 1 of the ~8-point grade 8 math decline; state population effects from EL change: Delaware -2.5, New Mexico -2.9, Illinois -2.3, Hawaii -2.1, Utah -2.1 NAEP points (EL share up at least 4pp, e.g. Delaware 4% to 10%)",
        estimate_unit="NAEP scale points of the state mean change attributable to composition",
        source_url="https://www.air.org/sites/default/files/2024-09/NVS-Population-Composition-508.pdf",
        source_locator="RQ2 national results and Exhibit 7; 'By Change in EL Status' and Exhibit 12",
        quote="\"The largest effect (nearly 1 point) is linked to changes in the EL population.\"; \"negative effects of 2 or more points were related to EL population changes in five states\"",
    ),
    dict(
        study="Neymotin 2009 [search find; ABSTRACT ONLY]",
        citation="Immigration and its effect on the college-going outcomes of natives. Economics of Education Review 28(5):538-550",
        country="US (California and Texas)",
        outcome_measure="[UNVERIFIED] SAT scores and college applications of public high-school students, 1994-2001 (SAT is a fixed national scale, low-stakes for the school) [SOURCE: abstract and ScienceDaily release only]",
        score_normalization_quote="[UNVERIFIED] full text not reached (paywalled; no working-paper copy found)",
        stakes="low-stakes for the school (SAT) [INFERENCE]",
        comparison="[UNVERIFIED] local census-place immigration matched to students; Hunt's WP describes it as a school-level analysis without an instrument",
        fixed_effects="[UNVERIFIED]",
        detects_statewide_shift="[UNVERIFIED] likely No or Partly",
        reason="Only two states, with place- or school-level variation; whether state-by-year terms are included cannot be checked without the full text.",
        headline_estimate="[UNVERIFIED] abstract: 1990s immigration \"did not harm, and possibly benefited\" natives' outcomes; no number reached",
        estimate_unit="[UNVERIFIED]",
        source_url="https://ideas.repec.org/a/eee/ecoedu/v28y2009i5p538-550.html",
        source_locator="abstract only",
        quote="\"I analyze immigration's effect on the SAT-scores and college application patterns of high school students in California and Texas.\" (abstract)",
    ),
]


def main() -> None:
    with OUT.open("w", newline="", encoding="utf-8") as fh:
        w = csv.DictWriter(fh, fieldnames=COLS, lineterminator="\n")
        w.writeheader()
        for r in ROWS:
            missing = set(COLS) - set(r)
            if missing:
                raise SystemExit(f"row {r.get('study')} missing {sorted(missing)}")
            w.writerow(r)
    print(f"wrote {len(ROWS)} rows -> {OUT}")


if __name__ == "__main__":
    main()
