"""Render derived/tables.md from the lane's own CSVs. No new numbers computed here."""
import csv
import json
import os

import cpmodel as M

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "derived")


def rd(name):
    with open(os.path.join(OUT, name), encoding="utf-8") as fh:
        return list(csv.DictReader(fh))


def tbl(head, rows):
    out = ["| " + " | ".join(head) + " |",
           "|" + "|".join("---" for _ in head) + "|"]
    out += ["| " + " | ".join(r) + " |" for r in rows]
    return out


def main():
    K = json.load(open(os.path.join(OUT, "paper_constants.json"), encoding="utf-8"))
    L = []

    L.append("# Calibration tables")
    L.append("")
    L.append("Generated by `make_tables.py` from this lane's `derived/` CSVs. "
             "Every number traces to `parameters.csv`, `tau_repo.csv`, `gate.csv`, "
             "`arms.csv` or `observed_migration.csv`, which carry the source column.")
    L.append("")

    L.append("## 1. Reproduction gate: the paper's Table 1 rebuilt from its own coefficients")
    L.append("")
    rows = []
    for r in rd("gate.csv"):
        rows.append([r["country"],
                     f"{float(r['delta_calc']):.4f} / {float(r['delta_paper']):.4f}",
                     f"{float(r['a_calc']):.4f} / {float(r['a_paper']):.4f}",
                     f"{float(r['tau_calc']):.3f} / {float(r['tau_paper']):.3f}",
                     f"{float(r['mstar_c0.5']):.4f}",
                     f"{float(r['mstar_over_m0']):.1f}x",
                     f"{float(r['phi_at_optimum']):.2f}"])
    L += tbl(["country", "delta ours/paper", "a ours/paper", "tau ours/paper",
              "m* at c=0.5", "vs m0=0.003", "phi=m*/a"], rows)
    L.append("")
    n_over = sum(1 for r in rd("gate.csv") if float(r["phi_at_optimum"]) > 1.0)
    L.append(f"The last column is a diagnostic the paper does not print: eq. (2) defines "
             f"`0 < phi < 1`, and at {n_over} of its 9 countries' own optimal rates phi exceeds 1.")
    L.append("")

    L.append("## 2. Repo-derived assimilation rates for the Mexican-origin lineage")
    L.append("")
    L.append(f"`a = -ln(gap_late/gap_early)/years`, one generation = 29 years, so the "
             f"G1 to G3+ column spans 58 years. Gaps are against third-plus non-Hispanic "
             f"whites. Rows marked `no` under 'usable' have a first-generation gap that is "
             f"not distinguishable from zero, so their implied rate is noise.")
    L.append("")
    rows = []
    for p in rd("parameters.csv"):
        rows.append([p["domain"], p["outcome"], p["usable"],
                     f"{float(p['g1']):.3f}", f"{float(p['g2']):.3f}", f"{float(p['g3']):.3f}",
                     f"{float(p['a_g1_g2']):.4f}", f"{float(p['a_g2_g3']):.4f}",
                     f"**{float(p['a_g1_g3']):.4f}**"])
    L += tbl(["domain", "outcome", "usable", "G1 gap", "G2 gap", "G3+ gap",
              "a G1-G2", "a G2-G3+", "a G1-G3+"], rows)
    L.append("")

    L.append("## 3. Repo-derived transmission rate for Mexico")
    L.append("")
    L.append(f"The paper's method: `tau = delta/gamma`, delta the education-, age- and "
             f"sex-conditional earnings gap of a new arrival at "
             f"{K['delta_years_since_arrival']:.0f} years since arrival, gamma the origin "
             f"TFP gap. gamma for Mexico is the paper's own Table 1 value.")
    L.append("")
    rows = [[t["construction"], t["n"],
             "" if t["mean_ysm"] == "nan" else f"{float(t['mean_ysm']):.1f}",
             f"{float(t['resid_lnw']):.4f}", f"{float(t['delta']):.4f}",
             f"{float(t['gamma']):.3f}", f"**{float(t['tau']):.4f}**"]
            for t in rd("tau_repo.csv")]
    L += tbl(["construction", "n", "mean years since arrival", "log-wage residual",
              "delta", "gamma", "tau"], rows)
    L.append("")

    L.append("## 4. Observed Mexican migration rate and stock")
    L.append("")
    L += tbl(["quantity", "value", "unit"],
             [[r["quantity"], r["value"], r["unit"]] for r in rd("observed_migration.csv")])
    L.append("")

    L.append("## 5. Optimal migration under the repo's parameters, and the arms that move it")
    L.append("")
    rows = [[a["arm"], a["a"], a["tau"], a["a_needed_for_positive_mstar"],
             a["mstar"], a["mstar_over_observed"] + "x", a["reverses_headline"]]
            for a in rd("arms.csv")]
    L += tbl(["arm", "a", "tau", "a needed for m*>0", "m*", "vs observed", "m* positive?"], rows)
    L.append("")

    L.append("## 6. Sign flip")
    L.append("")
    rows = [[s["kind"], s["basis"], s["a"], s["tau_flip"]] for s in rd("sign_flip.csv")]
    L += tbl(["kind", "basis", "a", "tau"], rows)
    L.append("")

    with open(os.path.join(OUT, "tables.md"), "w", encoding="utf-8") as fh:
        fh.write("\n".join(L) + "\n")
    print(f"tables.md written, {len(L)} lines")


if __name__ == "__main__":
    main()
